# Generated by Django 4.2.3 on 2023-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=300)),
                ("faculty", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
